# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVZa958MFCQYlVzBUs7NAUHBwM4x2rB2
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

#Tiêu đề ứng dụng
#st.title('Ứng dụng biểu đồ với Streamlit')

#Tạo dữ lieuẹ
x= np.linspace(0,10,100)
y= np.sin(x)

#Vẽ biểu đồ
plt.figure(figsize=(10,5))
plt.plot(x,y, marker='o')
plt.title('Biểu đồ xin(x)')
plt.xlabel('Giá trị x')
plt.ylabel('Giá trị y')

#Hiển thị biểu đồ trong streamlit
st.pyplot(plt)